erupt-app:
  # 登录失败几次，需要验证码
  version: 1.0.1
  versionMsg: 初始化框架
  verifyCodeCount: 10
erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 spring boot）
  redisSession: true
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: ${office_upload_path:D:/erupt/attachment}
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true
spring:
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-43bvjnay.sql.tencentcdb.com:24501/office?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: office
    password: Office123
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
  redis:
    host: 110.42.134.117
    port: 6379
    timeout: 20000
    # password:
    pool:
      minIdle: 0
      maxIdle: 8
      maxWait: -1
      maxActive: 8
  mail:
    username: xxxx@qq.com
    password: xxxxxxx
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS
  # 有环境变量用变量没有就：后面的
  port: ${office_port:8080}

